apiVersion: apps/v1
kind: Deployment
metadata:
  name: javadeployment
  namespace: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: javaapp
  template:
    metadata:
      name: javapod
      namespace: test
      labels:
        app: javaapp
    spec:
      containers:
      - name: javacontainer
        image: adhanduprolu/java-app:1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "300m"
            memory: "128Mi"
          limits:
            cpu: "600m"
            memory: "256Mi"
